# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#
# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do

  desc "Run all of unit tests for the project" 
  lane :tests do
    run_tests(scheme: "TIERMobilityTaskTests",
              buildlog_path: "./fastlane/fastlane-buildlog",
              derived_data_path: "~/Library/Developer/Xcode/DerivedData",
	      devices: ["iPhone 11"])
   end

    desc "Execute SwiftLint and compare current results with baseline"
    lane :lint do |options|
        swiftlint(
            mode: :lint,
            config_file: ".swiftlint.yml",
            output_file: ".swiftlint.result.json",
            ignore_exit_status: true,
            strict: false,
	    reporter: "checkstyle"
        )

        # method defined in helpers/swiftlint_analyzer.rb
        output = sh(
            command: "ruby helpers/swiftlint_analyzer.rb",
            log: false
        )
        if output.length() > 0
            UI.user_error!(output)
        end

        UI.success "SwiftLint comparison succeeded!"
        UI.success "No new issues found."
    end

end
